### ISSUE TITLE
在配置文件中保存 HTTP API 登录信息

### ISSUE THREAD

**Issue by CDN18** [DreamVoid/MiraiMC#412]
### 功能描述

目前要连接到外部MCL只能在启动服务器后手动输入命令，希望能在`config.yml`中加入HTTP API的登录信息配置，避免每次都要手动输入命令的麻烦。
```yml
http-api:
  url: http://localhost:8080
  message-fetch:
    interval: 10
    count: 10
  # 以下是对应的可能新增部分
  verifykey: key
  accounts:
    - 10000
    - 10001
```

### 使用方法

1. 参照文档和功能描述填写`config.yml`
2. 下次启动服务器时生效
